// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cosine_similarity_cpp
double cosine_similarity_cpp(NumericVector x, NumericVector y);
RcppExport SEXP _CosineSimilarity_cosine_similarity_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cosine_similarity_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// cosine_similarity_matrix_cpp
NumericMatrix cosine_similarity_matrix_cpp(NumericMatrix mat);
RcppExport SEXP _CosineSimilarity_cosine_similarity_matrix_cpp(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(cosine_similarity_matrix_cpp(mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CosineSimilarity_cosine_similarity_cpp", (DL_FUNC) &_CosineSimilarity_cosine_similarity_cpp, 2},
    {"_CosineSimilarity_cosine_similarity_matrix_cpp", (DL_FUNC) &_CosineSimilarity_cosine_similarity_matrix_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_CosineSimilarity(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
