# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cosine_similarity_cpp <- function(x, y) {
    .Call(`_CosineSimilarity_cosine_similarity_cpp`, x, y)
}

cosine_similarity_matrix_cpp <- function(mat) {
    .Call(`_CosineSimilarity_cosine_similarity_matrix_cpp`, mat)
}

